CREATE TABLE CATEGORY (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE TRANSACTION (
    id BIGSERIAL PRIMARY KEY,
    description VARCHAR(255),
    amount DECIMAL(19, 2) NOT NULL,
    date DATE NOT NULL,
    category_id BIGINT,
    FOREIGN KEY (category_id) REFERENCES CATEGORY(id)
);
